### ISSUE TITLE
How to view the examples?

### ISSUE THREAD

**Issue by faa-santos** [batterysim/equiv-circ-model#1]
Hello Mr.Wigging,

I'm not sure I understand how the code order works. I have python 3.8 installed with the numpy, scipy and matplotlib packages. Should I write in python the path to the directory where my code folder is? How do I view the examples?

I'm inexperienced in using python, I apologize if the question was too simple.

**Comment by wigging** [comment]
Before you can run the examples you need to install the `ecm` package. Did you install the `ecm` package using `pip install -e .`? This is discussed in the Installation section of the README.

**Comment by faa-santos** [comment]
Yes, now I was able to install the ecm package. I didn't know how to use the "cd" command in python, but knowing that, I managed to navigate through the folders and execute the files correctly.
The parameters I'm looking for are these:
             tau1: float
                 First time constant [s]
             tau2: float
                 Second time constant [s]
             r0: float
                 Series resistance [Ω]
             r1: float
                 Resistance in first RC branch [Ω]
             r2: float
                 Resistance in second RC branch [Ω]
             c1: float
                 Capacitance in first RC branch [F]
             c2: float
                 Capacitance in second RC branch [F]
Which are described in: ~ \ equiv-circ-model-master \ ecm \ cell_ecm.py

But I couldn't find their values for the different SOC values. Are they in a .csv file or are they just shown graphically?

**Comment by wigging** [comment]
The `cd` is a terminal command, not a Python command. It means "change directory" which allows you to move to different folders in the terminal.

If you run the **examples/cell/hppc_rctau.py** file it should print out the RC values in the terminal.

**Comment by faa-santos** [comment]
Thank you very much for your help!! And congratulations for the code!

**Comment by wigging** [comment]
Glad to help. If you have more questions then just submit another Issue.
